INSERT INTO INSUDB.FIELDSHEET (NSHEET,NFIELD,DCOMPDATE,NFIELDTYPE,STABLE,NUSERCODE,SFIELDDESC,SCOLUMNNAME,NFIELDORDER,NFIELDLARGE,SOBLIGATORY,SLASTMOVE,NDATATYPE,NOBJTYPE)
VALUES
(54740,11,SYSDATE,3,0,1771,'Dias','NDIAS',11,3,1,2,4,1)
/
COMMIT